name: Deploy to offrest.github.io

on:
  push:
    branches:
      - hotfix/deploy  # main 브랜치에 push할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout offrest
        uses: actions/checkout@v3

      - name: Set up GitHub App authentication
        run: |
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          gh auth status

      - name: Clone offrest.github.io
        run: |
          git clone https://github.com/offrest/offrest.github.io.git
          cd offrest.github.io
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy changes to offrest.github.io
        run: |
          cd offrest.github.io
          cp -r ../dist/* .  # 빌드된 파일 복사
          git add .
          git commit -m "Deploy from offrest"
          git push origin main